# Base configs
baseurl:
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Darkweb Kittens"
subtitle: "Putting the Cute Cat Theory into practice!"
author: "Anon"
header:
 title: "Darkweb Kittens"
footer:
 name: "Pictures of kittens... on the dark web."
 bio: "Work in progress...<br>Please stand by."