---
- name: wg show
  become: yes
  command: wg show
  register: wg_show
  changed_when: false
- debug: msg="{{ wg_show.stdout_lines|list }}"

- name: ip link show wg0
  become: yes
  command: ip link show wg0
  register: iplink_wg
  changed_when: false
- debug: msg="{{ iplink_wg.stdout_lines|list }}"
...